### ISSUE TITLE
Entering the "change seed" loop

### ISSUE THREAD

**Issue by znagzanglong** [lyh6560new/BotMoE#4]
Thank you very much for making your code public, but I ran into problems reproducing your results.I have been running this place for 2 days. Is there something wrong with my method?
![1695195163290](https://github.com/lyh6560new/BotMoE/assets/103175176/f83b7bfa-1b37-4778-8a90-0f85f853add9)

**Comment by MyFantasticWorld** [comment]
Maybe there are some issues in your try block in the main file, then the program enters error handling program.
